### ISSUE TITLE
Ignoring exception in on_connect & Database errors

### ISSUE THREAD

**Issue by newallin** [DiscordGIR/Bloo#23]
Method: Without Docker
Database: mongodb atlas

AttributeError: Database is not set up properly! Role 'role_memberplus' is missing. Please refer to README.md.

**Comment by newallin** [comment]
--nvm i am just stupid for anyone that wonders, do setup.py

**Comment by newallin** [comment]
What should I do? (Method: With docker)


```Traceback (most recent call last):
  File "/workspaces/Bloo/./main.py", line 9, in <module>
    from utils.database import db
  File "/workspaces/Bloo/utils/database.py", line 22, in <module>
    db = Database()
  File "/workspaces/Bloo/utils/database.py", line 18, in __init__
    if not Guild.objects(_id=cfg.guild_id):
  File "/opt/venv/lib/python3.10/site-packages/mongoengine/queryset/manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/opt/venv/lib/python3.10/site-packages/mongoengine/document.py", line 223, in _get_collection
    if cls._meta.get("auto_create_index", True) and db.client.is_primary:
  File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1088, in is_primary
    return self._server_property('is_writable')
  File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 889, in _server_property
    server = self._topology.select_server(
  File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 244, in select_server
    return random.choice(self.select_servers(selector,
  File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 202, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: host.docker.internal:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61c6c67ec4c24c5f3417e412, topology_type: Single, servers: [<ServerDescription ('host.docker.internal', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27017: [Errno 111] Connection refused')>]>```

**Comment by newallin** [comment]
This too.

```Failed to add command to guild 923629166585344001
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/discord/bot.py", line 716, in on_connect
    await self.register_commands()
  File "/opt/venv/lib/python3.10/site-packages/discord/bot.py", line 277, in register_commands
    cmds = await self.http.bulk_upsert_guild_commands(
  File "/opt/venv/lib/python3.10/site-packages/discord/http.py", line 332, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

            88          88                          
            88          88                          
            88          88                          
            88,dPPYba,  88  ,adPPYba,   ,adPPYba,   
            88P'    "8a 88 a8"     "8a a8"     "8a  
            88       d8 88 8b       d8 8b       d8  
            88b,   ,a8" 88 "8a,   ,a8" "8a,   ,a8"  
            8Y"Ybbd8"'  88  `"YbbdP"'   `"YbbdP"'   
                
[*] Logged in as: Ghost (ID)
[*] Version: 2.0.0a
[*] Made with ❤️ by SlimShadyIAm#9999 and the Bloo development team. Enjoy!
Task exception was never retrieved
future: <Task finished name='Task-47' coro=<fetch_issue_cache() done, defined at /workspaces/Bloo/utils/misc.py:53> exception=AttributeError("'NoneType' object has no attribute 'history'")>
Traceback (most recent call last):
  File "/workspaces/Bloo/utils/misc.py", line 62, in fetch_issue_cache
    async for message in channel.history(limit=None, oldest_first=True):
AttributeError: 'NoneType' object has no attribute 'history'```

**Comment by SlimShadyIAm** [comment]
So you're using Atlas? Because according to the first error you posted, it's trying to connect to a local database, not Atlas. 
![image](https://user-images.githubusercontent.com/10660846/147386227-f9dc0dc5-dc19-429c-8573-d7923b11aa36.png)
Make sure you set the `.env` file up correctly. Read the README.

**Comment by newallin** [comment]
Yup, then I used atlas and received the second error, the missing acesss one.

**Comment by SlimShadyIAm** [comment]
> ```discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access```

This is because you need to invite the bot to your server with the `application.commands` scope set. See this: https://docs.pycord.dev/en/master/discord.html#inviting-your-bot

> ```AttributeError: 'NoneType' object has no attribute 'history'```

You haven't set up the `channel_common_issues` field in the database. If you don't want to use that feature you should comment out the code.

**Comment by newallin** [comment]
How can I comment out channel_common_issues?

**Comment by SlimShadyIAm** [comment]
Actually just comment out `bot.issue_cache = IssueCache(bot)` in `main.py`

**Comment by newallin** [comment]
Okay thank you.

**Comment by newallin** [comment]
![image](https://user-images.githubusercontent.com/88211082/147386411-979fd1ab-5725-417c-a6eb-d4e913f19c51.png)
Its already set up though.

**Comment by newallin** [comment]
It gives me this now, I ran setup.py with my own guild ID
```Exception: The database has not been set up for guild 0! Please refer to README.md.```


--nevermind

**Comment by SlimShadyIAm** [comment]
> ![image](https://user-images.githubusercontent.com/88211082/147386411-979fd1ab-5725-417c-a6eb-d4e913f19c51.png) Its already set up though.

Did you re-invite the bot after setting it? The invite URL needs to have the `application.commands` scope set.

**Comment by newallin** [comment]
Thank you, it works.
